name: GithubCI

on:
  push:
    branches: [ master ]
  pull_request:

env:
  CALCROM_DISCORD_WEBHOOK_USERNAME: ${{ secrets.CALCROM_DISCORD_WEBHOOK_USERNAME }}
  CALCROM_DISCORD_WEBHOOK_AVATAR_URL:  ${{ secrets.CALCROM_DISCORD_WEBHOOK_AVATAR_URL }}
  CALCROM_DISCORD_WEBHOOK_URL:  ${{ secrets.CALCROM_DISCORD_WEBHOOK_URL }}

jobs:
  build:
    runs-on: ubuntu-latest
    steps:

      - name: Checkout repo
        uses: actions/checkout@master

      - name: Checkout agbcc
        uses: actions/checkout@master
        with:
          path: agbcc
          repository: pret/agbcc

      - name: Install xdelta and ARM GCC
        run: |
            sudo apt update
            sudo apt-get install xdelta3 gcc-arm-none-eabi binutils-arm-none-eabi libpng-dev

      - name: Install agbcc
        run: |
          ./build.sh
          ./install.sh ../
        working-directory: agbcc

      - name: Build tools and baserom
        run: |
          cd $GITHUB_WORKSPACE
          make tools
          head -c 33554432 /dev/zero > tmp.bin
          xdelta3 -d -s tmp.bin baserom.xdelta baserom.gba
          rm tmp.bin

      - name: Build via Makefile
        run: |
          make -j${nproc} compare

      - name: Modern
        run: |
          make -j${nproc} modern

      # only run OK when pushed to master
      - name: Run OK webhook
        shell: bash
        if: ${{ github.event_name == 'push' }}
        run: |
          sudo chmod 755 $GITHUB_WORKSPACE/.github/calcrom/webhook.sh
          $GITHUB_WORKSPACE/.github/calcrom/webhook.sh pmd_red "$CALCROM_DISCORD_WEBHOOK_URL"
        continue-on-error: true
